version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: parkpointsolutions_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
     - "${DB_PORT}:5432"
    volumes:
      - parkpointsolutions_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: parkpointsolutions_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - parkpointsolutions_mongo_data:/data/db

volumes:
  parkpointsolutions_data:
  parkpointsolutions_mongo_data:
